services:
  testepratico_app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: "testepratico_app"
    user: "${UID}:${GID}"
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    env_file:
      - .env
    networks:
      - app_network

  testepratico:
    image: mysql:8.0
    container_name: "testepratico"
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge